// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgU50peSxtSmhDZxL_elB2V9_D9mJ3YYk',
    appId: '1:270246260737:web:70b39c6e7a3b32607c9000',
    messagingSenderId: '270246260737',
    projectId: 'flutter-fcm-18bb1',
    authDomain: 'flutter-fcm-18bb1.firebaseapp.com',
    storageBucket: 'flutter-fcm-18bb1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKfeY-noPUBfLbKciijWpnCCLsXPuk0ZM',
    appId: '1:270246260737:android:6d0170794c46fdb67c9000',
    messagingSenderId: '270246260737',
    projectId: 'flutter-fcm-18bb1',
    storageBucket: 'flutter-fcm-18bb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoLo1BOEIVgDLZNzm6zi_LBTSJQhPBztc',
    appId: '1:270246260737:ios:0863e63696d8cafd7c9000',
    messagingSenderId: '270246260737',
    projectId: 'flutter-fcm-18bb1',
    storageBucket: 'flutter-fcm-18bb1.appspot.com',
    iosClientId: '270246260737-tu7munp5fenifuagn3am4tgvhq2hu40u.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFcm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoLo1BOEIVgDLZNzm6zi_LBTSJQhPBztc',
    appId: '1:270246260737:ios:6159cd61174ebe647c9000',
    messagingSenderId: '270246260737',
    projectId: 'flutter-fcm-18bb1',
    storageBucket: 'flutter-fcm-18bb1.appspot.com',
    iosClientId: '270246260737-bt8pd7d86m9jqht3e5q2t5ujk626akae.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFcm.RunnerTests',
  );
}
